Document: python-webcoun
Title: Debian python-webcoun Manual
Author: <insert document author here>
Abstract: This manual describes what python-webcoun is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-webcoun/python-webcoun.sgml.gz

Format: postscript
Files: /usr/share/doc/python-webcoun/python-webcoun.ps.gz

Format: text
Files: /usr/share/doc/python-webcoun/python-webcoun.text.gz

Format: HTML
Index: /usr/share/doc/python-webcoun/html/index.html
Files: /usr/share/doc/python-webcoun/html/*.html
